### ISSUE TITLE
Won'tn play DCP

### ISSUE THREAD

**Issue by paddyb2** [Karleener/FreeDcpPlayer#1]
Thanks for developing this app. I am using Ryzen 5 3600 + GTX 1060 3gb.

The DCP opens, but hangs on the first frame forever. I tried using CroBa as well as my own DCP's.

Any thoughts as to where I'm going wrong?

**Comment by Karleener** [comment]
Hi,
When the first reel is opened , the first frame is displayed, then the program stop, this is normal. You have to press the space bar in order to play/stop. If the DCP is still not playing, try to click on the first frame in order to give the focus to the display window, then press space bar. If it is still blocked, please copy/paste here the content of the file "freedcpplayer.log" so that I can try to understand what happens. Is it a laptop ? Are you using a specific keyboard ?

**Comment by paddyb2** [comment]
Thanks so much for getting back to me.  I now have it working, I watched
your video, but don't speak French, so I missed the bit about the space
bar. Thanks for developing the app.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Karleener** [comment]
Nice, I will probably add some help in the next version which should also allow to play 4K, around september. I close this issue since it's solved, don't hesitate to add other comments.
