### ISSUE TITLE
Encrypted DCP Not working 

### ISSUE THREAD

**Issue by priyankoivan** [Karleener/FreeDcpPlayer#5]
I have an Encrypted DCP file.  i also have the kdm file but freedcpPlayer not able to play

**Comment by Karleener** [comment]
Hi. As I already answered, it's not an issue, it's an unsupported feature. I don't plan to add encrypted DCP support, since freedcpplayer is made for independant filmmakers before to submit a DCP for short films to festivals, and festivals usually ask DCP not encrypted. Some commercial product such as EasyDCP are supporting GPU accelerated decoding and encrypted DCP.

**Comment by priyankoivan** [comment]
thank you. i want to create dcp player which run on GPU . i also run freedcpplayer code in Visual Studio 2022. but I am not able to add kdm decryption. can you help me a little bit so that I can add kdm decryption?
